name: MicroPython Code Validation

on:
  push:
    branches:
      - main

jobs:
  validate_code:
    runs-on: windows-10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Validate MicroPython Code
      uses: docker://python:3.8

      with:
        args: |
          echo "Running MicroPython code validation" &&
          cd MicroPython &&
          python -m pip install esptool &&
          python -m pip install -U platformio &&
          python -m pip install -r requirements.txt &&
          platformio check -e esp8266
