name: MicroPython Code Validation

on:
  push:
    branches:
      - main

jobs:
  validate_code:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-10, windows-11, redhat-latest, ubuntu-latest, centos-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Validate Code
      uses: docker://${{ matrix.os }}

      with:
        args: |
          echo "Running MicroPython code validation" &&
          cd MicroPython &&
          apt-get update && apt-get install -y python3 ||
          yum install -y python3 ||
          dnf install -y python3 ||
          echo "No package manager found for the current OS" &&
          python3 -m pip install esptool &&
          python3 -m pip install -U platformio &&
          python3 -m pip install \
            adafruit-ampy \
            bitarray \
            bitstring \
            certifi \
            cffi \
            charset-normalizer \
            click \
            colorama \
            colorclass \
            cryptography \
            docopt \
            ecdsa \
            esptool \
            idna \
            intelhex \
            packaging \
            pip-upgrader \
            pycparser \
            pyreadline \
            pyserial \
            python-dotenv \
            pyudev \
            PyYAML \
            reedsolo \
            requests \
            rshell \
            setuptools \
            six \
            terminaltables \
            urllib3